Сверстать радио-кнопки; fix #3
IgorYarutkin/mishka pull request #7
Opened 2016-10-09 18:27 UTC by IgorYarutkin

#3

2016-10-21 09:59 UTC, isqua commented on app/blocks/radio-button/radio-button.jade
> +		+e('input').input(name='#{ content.name }' type='radio' id='#{ content.id }-' + (index+1) checked='#{ content.checked }')
Короче можно делать просто
```
name=content.name checked=content.checked
```
с id наверное так не выйдет.

2016-10-21 09:59 UTC, isqua commented on app/blocks/radio-button/radio-button.jade
> +		+e('label').label(for='#{ content.id }-' + (index+1)) #{ content.label }
Но от `id` вообще можно избавиться, если сам блок radio-button сделать лейблом.

2016-10-23 10:46 UTC, isqua commented on app/data/radio-buttons-list.json
> +[
Это не нужно. В стайлгайде нет никаких данных, это просто примеры блоков. Поэтому давай не будем в `data` хранить лишние сущности.

2016-10-23 10:47 UTC, isqua commented on app/pages/styleguide.jade
> +	+radio-buttons-list(getData('radio-buttons-list'))
Стайлгайд должен быть максимально простым: это просто примеры блоков. Чтобы ты мог открыть этот файл и увидеть, какие есть блоки и какие параметры в них можно передавать. Сейчас же тут какая-то сложная конструкция и не понятно, что происходит, нужно лезть в `blocks/radio-buttons-list/radio-buttons-list.jade` и в ` app/data/radio-buttons-list.json`, чтобы понять, что здесь происходит.

2016-10-23 11:19 UTC, isqua commented on app/styles/helpers/variables.styl
> +color-turquoise = #63d1bb
Знаешь, что за цвет такой «тиффани»?
<img width="265" alt="screenshot_20_10_16_17_49" src="https://cloud.githubusercontent.com/assets/529247/19564877/a8794b08-96ed-11e6-95cb-fe6aff5821e0.png">

2016-10-23 11:19 UTC, isqua commented on app/blocks/radio-button/radio-button.styl
> +		&:after
`::`

2016-10-23 11:31 UTC, isqua commented on app/blocks/radio-button/radio-button.styl
> +			position absolute
Кишки выпадают из блока, отступов между блоками нет:

<img width="359" alt="debug_ _examples" src="https://cloud.githubusercontent.com/assets/529247/19625872/42f2dd66-992d-11e6-999f-443d7fae2dbf.png">

Десктопных размеров нет.

2016-10-23 11:32 UTC, isqua commented on app/blocks/radio-button/radio-button.jade
> +		+e('input').input(name='#{ content.name }' type='radio' id='#{content.id}-' + (index+1) checked=content.checked)
`name='#{ content.name }'`  → `name=content.name`

2016-10-23 11:33 UTC, isqua commented on app/blocks/radio-button/radio-button.jade
> +		+e('label').label(for='#{content.id}-'+(index+1))= content.label
Можешь придумать что-нибудь, чтобы не передавать id в каждый радио?

2016-10-23 11:34 UTC, isqua commented on app/blocks/radio-button/radio-button.jade
> +mixin radio-button(content, index)
Может, переименовать блок в `radio` для краткости?

2016-10-23 11:35 UTC, isqua commented
Короче, то что надо не сделано, а то что не надо сделано. Задача не решена. Две недели уже висит!

2016-10-23 17:02 UTC, IgorYarutkin commented on app/blocks/radio-button/radio-button.jade
> +mixin radio-button(content, index)
Сделано

2016-10-23 19:47 UTC, isqua commented on app/data/radio-buttons-list.json
> +[
Файл-то удалить можно?

2016-10-23 19:49 UTC, isqua commented on app/blocks/radio/radio.jade
> +			+e('input').input(name='#{ content.name }' type='radio' checked=content.checked)
`name=content.name`?

2016-10-23 19:49 UTC, isqua commented on app/blocks/radio/radio.jade
> +		+e('label').label= content.label
А сам-то блок radio нельзя лейблом сделать?

2016-10-23 19:50 UTC, IgorYarutkin commented on app/data/radio-buttons-list.json
> +[
Сделано

2016-10-23 19:52 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +			+e('input').input(name='#{ content.name }' type='radio' checked=content.checked)
Сделано. А в чем разница? В том, что до этого я записывал значение в атрибут. А так записываю значение в свойство html- элемента?

2016-10-23 19:55 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +		+e('label').label= content.label
Наверное можно... Завтра поменяю. Стили надо переделывать и тестировать

2016-10-23 19:55 UTC, isqua commented on app/blocks/radio/radio.styl
> +			left -61px
А самому-то `__check` нельзя эти стили навешать? Зачем псевдо-элемент?

2016-10-23 19:56 UTC, isqua commented on app/blocks/radio/radio.jade
> +			+e('input').input(name='#{ content.name }' type='radio' checked=content.checked)
А свойство хтмл-элемента это не атрибут?

2016-10-23 19:59 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +			+e('input').input(name='#{ content.name }' type='radio' checked=content.checked)
Тогда не понимаю в чем разница этих двух вариантов написания? Можно писать название переменной потому, что она и так строка?

2016-10-23 20:00 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +			left -61px
Ну как минимум один-то псеводэлемент всего равно понадобится. Для кружочка-галочки

2016-10-23 20:04 UTC, isqua commented on app/blocks/radio/radio.styl
> +			left -61px
Да, для внутреннего понадобится. А для наружного зачем? Зачем тебе два псевдо-элемента, когда нужен один?

2016-10-23 21:42 UTC, isqua commented on app/blocks/radio/radio.jade
> +			+e('input').input(name='#{ content.name }' type='radio' checked=content.checked)
В том, что второй короче?

> Можно писать название переменной потому, что она и так строка?

Да.

2016-10-24 16:22 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +		+e('label').label= content.label
Сделано. Стили менять не пришлось...

2016-10-24 16:58 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +			left -61px
Сделано

2016-10-24 18:42 UTC, isqua requested changes

2016-10-24 18:42 UTC, isqua commented on app/blocks/radio/radio.styl
> +		position absolute
Зачем его абсолютить теперь?

2016-10-24 18:42 UTC, isqua commented on app/blocks/radio/radio.styl
> +				left 15px
Можно кружок маленький просто всегда по центру большого позиционировать, чтобы на разных разрешениях не приходилось менять топ/лефт?

2016-10-24 18:42 UTC, isqua commented on app/blocks/radio/radio.styl
> +		^[0]__label:hover &
Я не могу прочитать этот селектор.

2016-10-24 18:42 UTC, isqua commented on app/pages/styleguide.jade
> +//	+radio-buttons-list(getData('radio-buttons-list'))
Убрать.

2016-10-24 18:42 UTC, isqua commented on app/styles/helpers/variables.styl
> +color-decorate = #63d1bb
Давай вот этот цвет в переменную `tiffany` засунем, а потом будет писать типа `icon-hover-color = tiffany`, `color-decorat = tiffany`?

2016-10-24 18:42 UTC, isqua commented on app/blocks/radio/radio.styl
> +		height 38px
А измерь ещё чекбоксы? Как думаешь, чекбоксы и радио должны быть одного размера?

2016-10-24 19:11 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		height 38px
Сделал 40рх

2016-10-24 19:13 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		^[0]__label:hover &
http://stylus-lang.com/docs/selectors.html#partial-reference

2016-10-24 19:17 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +				left 15px
Можно... Вот только пока не идет в голову как это сделать...

2016-10-24 19:17 UTC, IgorYarutkin commented on app/pages/styleguide.jade
> +//	+radio-buttons-list(getData('radio-buttons-list'))
Сделано

2016-10-24 19:53 UTC, isqua commented on app/blocks/radio/radio.jade
> +		+e('span').label= content.label
Так а для чего вот этот спан?

2016-10-24 19:54 UTC, isqua commented on app/blocks/radio/radio.styl
> +				left 15px
То есть ты не умеешь центровать блок по вертикали и горизонтали?

2016-10-24 20:08 UTC, IgorYarutkin commented on app/styles/helpers/variables.styl
> +color-decorate = #63d1bb
Сделано

2016-10-24 20:09 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +		+e('span').label= content.label
Переписал немного... Для подписи радио-батона

2016-10-24 20:09 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		^[0]__label:hover &
Изменил

2016-10-24 20:09 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +				left 15px
Чё чразу "не умеешь!..." :) 
Умею... Подумать нельзя что-ли? :)
Сделано

2016-10-24 20:09 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		position absolute
Сделано

2016-10-24 20:50 UTC, isqua commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Ох развращают вас флексы :)

2016-10-25 06:32 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
А что? Использовать флексы плохо? 
Конечно я могу задать инлайн-блок элементам радио...
Переделать?

2016-10-25 08:07 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Переделал на инлайн-блоки.
В ветке issues/3_1 лежит этот вариант

2016-10-25 11:23 UTC, isqua commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Да нет, не плохо.

2016-10-25 11:24 UTC, isqua commented
Пофикси выхлоп вот этих ребят:
```
npm run lint:templates
npm run lint:styles
```
стили тебе надо будет пересортировать по порядку, который указан в файле `.stylintrc`

2016-10-25 11:25 UTC, isqua commented on app/blocks/radio/radio.styl
> +	margin-bottom 15px
Вот это число меня тоже смущает. Нет ли в макете бага?

2016-10-25 11:26 UTC, isqua commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
А инлайн-блоки твои не развалятся от переполнения-то?

2016-10-25 11:28 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Не тестил...

2016-10-25 11:29 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +	margin-bottom 15px
По макету 20рх. А по ПП получается 15рх

2016-10-25 11:32 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Флоаты+инлайн-блоки Vs Флексбоксы?
Я умею верстать на флоатах и инлайнах. Помучаюсь побольше и сделаю в 90% случаев как надо.
Но можно уже полностью верстать на флексах?

2016-10-25 11:37 UTC, isqua commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Да я не говорю, что нельзя. Просто заметила, что флексы развращают :)

2016-10-25 11:38 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		flex-shrink 0
Ну и ладно... Буду опытным развращенцем 😬

2016-10-25 13:19 UTC, IgorYarutkin commented
Сделано
>Пофикси выхлоп вот этих ребят:
```npm run lint:templates
npm run lint:styles```

2016-10-25 13:56 UTC, isqua commented
> Сделано

Ну так запушь!

2016-10-25 14:00 UTC, IgorYarutkin commented
Запушил

2016-10-25 14:17 UTC, isqua commented on app/blocks/radio/radio.jade
> +		+e('input').input(name=content.name type='radio' checked=content.checked)
Так, а как насчёт value?

2016-10-26 06:21 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +		+e('input').input(name=content.name type='radio' checked=content.checked)
Забыл про него :(

2016-10-26 08:06 UTC, IgorYarutkin commented on app/blocks/radio/radio.jade
> +		+e('input').input(name=content.name type='radio' checked=content.checked)
Сделано

2016-10-26 10:05 UTC, isqua commented on app/blocks/radio/radio.styl
> +	margin-bottom 15px
Давай как в макете, сделаем 20?

2016-10-26 10:05 UTC, isqua commented on app/blocks/radio/radio.styl
> +		margin-bottom 24px
А у чекбоксов такой же?

2016-10-26 11:43 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		margin-bottom 24px
У радио: мобилка - 20рх, планшет и десктоп - 24рх
У чекбоксов: мобилка - 22рх, планшет и десктоп - 24рх

2016-10-26 11:44 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +	margin-bottom 15px
Тогда на мобилке у радио и чекбоксов - 20рх, а планшет и десктоп - 24рх?

2016-10-26 16:00 UTC, isqua commented on app/blocks/radio/radio.styl
> +		margin-bottom 24px
Ну давай сделаем везде на мобиле 20, на планшете и десктопе 24?

2016-10-27 07:30 UTC, IgorYarutkin commented on app/blocks/radio/radio.styl
> +		margin-bottom 24px
Сделано

2016-10-27 10:32 UTC, isqua approved these changes
🎱  сквошься и вливай

2016-10-27 14:52 UTC, merged