Issues/4
IgorYarutkin/mishka pull request #8
Opened 2016-10-25 12:55 UTC by IgorYarutkin

#4

2016-10-27 07:37 UTC, IgorYarutkin commented
Маргины между блоками подправил

2016-10-27 07:39 UTC, IgorYarutkin commented
Подправил маргины между блоками как в радио

2016-10-27 17:40 UTC, IgorYarutkin commented
Отребейзил

2016-10-28 20:59 UTC, isqua requested changes

2016-10-28 20:59 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +		vertical-align top
А для чего `vertical-align`?

2016-10-28 20:59 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +			transform translateX(-50%) translateY(50%)
А вот это кажется тот случай, когда можно не париться с выравниванием штуки по центру родителя, а растянуть этот блок на всю ширину и задать bg-size и bg-position.

2016-10-28 20:59 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +		display inline-block
Это для чего, если у тебя флексы?

2016-10-28 20:59 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +		vertical-align top
И вот это?

2016-10-28 20:59 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +		width 80%
А ширина зачем?

2016-10-28 20:59 UTC, isqua commented on app/resources/assets/images/checkmark.svg
> +<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg">
Картинка, во-первых, странная, не похожа на макет. Во-вторых, её нужно пожать.

2016-10-29 05:20 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +		vertical-align top
По всей видимости остался в наследство от `display: inline-block`
Убрал

2016-10-29 05:21 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +		display inline-block
Наследство...
Убрал

2016-10-29 05:21 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +		width 80%
Наследство... Убрал

2016-10-29 05:22 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +		vertical-align top
Наследство... Убрал

2016-10-29 06:27 UTC, IgorYarutkin commented on app/resources/assets/images/checkmark.svg
> +<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg">
Картинку поменял. Минификацию сделал

2016-10-29 06:38 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +			transform translateX(-50%) translateY(50%)
Сделано

2016-10-30 13:38 UTC, isqua commented
> Наследство...
> Убрал

Поэтому и надо заглядывать самому в дифф пулл-реквеста, и смотреть его глазами, и чинить _до того_, как зовёшь ревьюверов, _во время_ ревью  и _после_ ревью перед влитием тоже окинуть взглядом свой код не мешает.

2016-10-30 14:09 UTC, isqua commented
https://travis-ci.org/IgorYarutkin/mishka

Я не вижу, что репозиторий включен

2016-10-30 14:10 UTC, isqua requested changes
Сам чекбокс мне нравится, за исключением иконки-галочки.

2016-10-30 14:10 UTC, isqua commented on gulpfile.js
> +'use strict';
Теперь у тебя два галпфайла: этот и [gulpfile.babel.js](https://github.com/IgorYarutkin/mishka/blob/master/gulpfile.babel.js). При команде [npm start](https://github.com/IgorYarutkin/mishka/blob/master/package.json#L7) запускается твой новый `gulpfile.js`. Это приводит к ошибке:

```
npm start

> mishka@0.0.1 start ~/.../mishka
> gulp --debug

[16:47:29] Using gulpfile ~/.../gulpfile.js
[16:47:29] Task 'default' is not in your gulpfile
[16:47:29] Please check the documentation for proper gulpfile formatting

npm ERR! ...
```

Запустить приложение теперь невозможно. Вопрос: как ты проверил результат, что новая и пожатая картинка хороша и подходит?

2016-10-30 14:10 UTC, isqua commented on app/resources/assets/images/checkmark.svg
> +<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"><title>background</title><path stroke="#000" stroke-width="4" fill="none" d="M0 17l12 10"/><path stroke-linecap="undefined" stroke-linej
Этот файл не используется? Зачем он тогда?

2016-10-30 14:10 UTC, isqua commented on app/pages/styleguide.jade
> +		h2(style="margin:10px 0") Примеры радио-кнопок
Если тебя беспокоит, что в стайлгайде не хватает оформления, создай какой-нибудь CSS-файл, который будешь подключать только на эту страницу.

И такие штуки надо делать делать отдельным коммитом, потому что к созданию чекбокса вот этот дифф не имеет никакого отношения.

2016-10-30 14:10 UTC, isqua commented on gulpfile.js
> +gulp.task('svg-min', function () {
А вообще ты планируешь запускать эту таску руками, или добавить в сборку типа gulp build, gulp deploy?

2016-10-30 14:10 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +	cursor pointer
Вот эту строку про курсор и в радио не мешает добавить, но отдельным коммитом.

2016-10-30 16:50 UTC, IgorYarutkin commented on gulpfile.js
> +'use strict';
Я запустил задачу в новом gulpfile.js `gulp svg-min`

2016-10-30 16:52 UTC, IgorYarutkin commented on gulpfile.js
> +gulp.task('svg-min', function () {
Сейчас я запускал ее руками. Но КМК правильнее добавить в сборку. Вот только еще добавить бы хитрую обработку, чтобы она проверяла минифицировали мы этот файл до этого или нет

2016-10-30 16:53 UTC, IgorYarutkin commented
Тревис включил.
А что не так с галочкой?

2016-10-30 16:54 UTC, isqua commented on gulpfile.js
> +'use strict';
Как ты запустил эту задачу — понятно. Не понятно, как потом ты проверил свою вёрстку с новой картинкой.

2016-10-30 16:55 UTC, IgorYarutkin commented on gulpfile.js
> +'use strict';
Ааа... у меня сервер был уже запущен. Поэтому он и отработал на новой картинке

2016-10-30 17:09 UTC, isqua commented on gulpfile.js
> +gulp.task('svg-min', function () {
> Вот только еще добавить бы хитрую обработку, чтобы она проверяла минифицировали мы этот файл до этого или нет

И сама пушила минифицированные картинки в репозиторий? Или половина картинок будут минифицированы, а другая половина — не минифицированны? По какому критерию отличить картинку, которую ещё можно сжать, от той, которую сжать нельзя?

2016-10-30 17:09 UTC, isqua commented
А галочка на планшете и десктопе чот не похожа на макет.

2016-10-30 17:13 UTC, isqua commented on gulpfile.js
> +gulp.task('svg-min', function () {
В разных командах принято по-разному работать с картинками. Но мой опыт вот какой:

Сборка и деплой занимают много времени, и нужно стараться их оптимизировать. Очевидно, что во время разработки код изменяется каждый день. Так же очевидно, что минифицированный код очень трудно редактировать вручную и никто так не делает. Поэтому мы при каждой сборке компилируем стили и скрипты.

Но картинки не меняются каждый день. Бывает, что появляются новые картинки, или удаляются старые. Но никто не открывает их руками и не редактирует.

Поэтому картинки нужно складывать в репозиторий уже минифицированными. Минифицированную картинку всё ещё можно открыть в фотошопе или иллюстраторе и поправить. Минификация не ухудшает редактируемость картинки. Но зато если хранить только минифицированные картинки в репозитории и при сборке не запускать минификацию, экономится драгоценное время.

Конечно, если ты делаешь сложный проект с демонстрацией возможностей SVG, и пишешь их руками, то будешь хранить их в удобном для редактирования виде. Потому что это и есть твои _исходники_.

Но в данном случае картинки — просто готовые кирпичики, с которыми ты работаешь.

Поэтому я предлагаю таску про минификацию убрать, и минифицировать картинки самостоятельно перед добавлением в репозиторий. Я использую [svgo](https://github.com/svg/svgo) и [imgo](https://github.com/imgo/imgo) для свг и растровых картинок соответственно.

2016-10-30 17:14 UTC, IgorYarutkin commented on gulpfile.js
> +gulp.task('svg-min', function () {
Не... Я не имел в виду различать "можно еще больше сжать этот svg или нет". 
Я имел в виду только сравнение с тем, что был этот файл обработан или нет. Как у Кантора в скринкасте про gulp.
Т.е. мы в первый раз мы пропускаем все svg через этот плагин и записываем данные этих файлов в какой-то свой файл. В следующий раз при срабатывании вотчера мы проверяем каждый svg и пропускаем через плагин только те, данные которых не записаны в нашем файле. 
Как-то так...

2016-10-30 17:16 UTC, IgorYarutkin commented on app/resources/assets/images/checkmark.svg
> +<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"><title>background</title><path stroke="#000" stroke-width="4" fill="none" d="M0 17l12 10"/><path stroke-linecap="undefined" stroke-linej
> Но в данном случае картинки — просто готовые кирпичики, с которыми ты работаешь.
>Поэтому я предлагаю таску про минификацию убрать, и минифицировать картинки самостоятельно перед добавлением в репозиторий. Я использую svgo и imgo для свг и растровых картинок соответственно.
Понял.

2016-10-30 17:17 UTC, IgorYarutkin commented on gulpfile.js
> +gulp.task('svg-min', function () {
> Но в данном случае картинки — просто готовые кирпичики, с которыми ты работаешь.
> Поэтому я предлагаю таску про минификацию убрать, и минифицировать картинки самостоятельно перед добавлением в репозиторий. Я использую svgo и imgo для свг и растровых картинок соответственно.

Понял. Удалил gulpfile.js

2016-10-30 17:36 UTC, isqua commented on package.json
> +    "gulp-svgmin": "^1.2.3",
.

2016-10-30 17:48 UTC, IgorYarutkin commented on app/resources/assets/images/checkmark.svg
> +<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg"><title>background</title><path stroke="#000" stroke-width="4" fill="none" d="M0 17l12 10"/><path stroke-linecap="undefined" stroke-linej
Удалил

2016-10-31 05:19 UTC, IgorYarutkin commented on app/pages/styleguide.jade
> +		h2(style="margin:10px 0") Примеры радио-кнопок
Убрал стили из styleguide.jade
Решил последовать твоему совету и не стилизовать эту страницу вообще

2016-10-31 05:23 UTC, IgorYarutkin commented
Галочку подправил по ПП. Мне кажется похоже на макет. Только моя чуть толще. Пробовал в svg-файле `"stroke-width=0.5"` ставить. Почему-то не работает

2016-10-31 05:24 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +	cursor pointer
Отдельным ПР вливать? Ведь я ПР по радио уже закрыл

2016-10-31 14:41 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +			background-image url('../images/icon-yes.svg')
Пути давай абсолютные писать?

2016-10-31 14:43 UTC, isqua commented
Ну и давай сквошиться :)

2016-10-31 18:47 UTC, IgorYarutkin commented
Так что с ПР? Принят?

2016-10-31 18:50 UTC, isqua commented
Да. Шар означает можно сквошиться и вливать.

2016-10-31 18:50 UTC, isqua approved these changes

2016-10-31 18:51 UTC, IgorYarutkin commented
Так ты свой реквест не сняла :)
P.S. Почему шар? И с 8-кой

2016-10-31 18:51 UTC, merged

2016-10-31 18:52 UTC, IgorYarutkin commented
Блин.... Пути забыл подправить... :(

2016-10-31 18:52 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +			background-image url('../images/icon-yes.svg')
Абсолютные это от корня сервера?

2016-10-31 18:52 UTC, isqua commented
> Так ты свой реквест не сняла :)

Да сорян. Теперь ок.

> Блин.... Пути забыл подправить... :(

Поправь отдельным пр.

2016-10-31 18:55 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +			background-image url('../images/icon-yes.svg')
А они как идут? 
`url('/assets/images/icon-yes.svg')`
Так?

2016-11-01 10:22 UTC, isqua commented on app/blocks/checkbox/checkbox.styl
> +			background-image url('../images/icon-yes.svg')
> Абсолютные это от корня сервера?

Да.

> А они как идут? 

Вопрос к тебе.

2016-11-01 12:38 UTC, IgorYarutkin commented on app/blocks/checkbox/checkbox.styl
> +			background-image url('../images/icon-yes.svg')
От корня сайта. 
Учитывая, что index.html лежит в корне сайта, то путь будет как бы от него:
``url('/assets/images/icon-yes.svg')```