Сверстать кнопку; fix #5
IgorYarutkin/mishka pull request #9
Opened 2016-10-26 14:58 UTC by IgorYarutkin

#5

2016-10-28 15:06 UTC, isqua commented
Ребейз?

2016-10-29 06:41 UTC, IgorYarutkin commented
Я тоже думал, что он поможет...

2016-10-31 14:59 UTC, isqua requested changes

2016-10-31 14:59 UTC, isqua commented on app/pages/styleguide.jade
> +>>>>>>> 571239f... Сверстать кнопку
Кто не посмотрел в дифф после того, как отребейзил?

2016-10-31 14:59 UTC, isqua commented on app/blocks/button/button.jade
> +	+b('button').button&attributes(attributes)(type="submit")= content.label
Залила тебе в ветку keks шрифты, картинки и спеку. [Из спеки](https://github.com/IgorYarutkin/mishka/blob/keks/Specification.md) становится ясно, что некоторые кнопки — это на самом деле ссылки. Надо эту проблему решить, что у тебя бывают и кнопки и ссылки, но выглядят они одинаково.

Ещё нужно учесть что бывают `<button type="button">` и `<button type="submit">`.

2016-10-31 14:59 UTC, isqua commented on app/blocks/button/button.styl
> +	padding 12px 0
Что, нулевые горизонтальные паддинги? Ох не сладко будет тексту в кнопке.

2016-10-31 14:59 UTC, isqua commented on app/blocks/button/button.styl
> +	font-size 17px
А line-height какой?

2016-10-31 14:59 UTC, isqua commented on app/blocks/button/button.styl
> +		width 230px
Чо там с переполнением?

2016-10-31 15:00 UTC, isqua commented
Вместо ссылки на ишью получился заголовок:

![_ __fix__5_by_igoryarutkin_ _pull_request__9_ _igoryarutkin_mishka](https://cloud.githubusercontent.com/assets/529247/19858762/d016592c-9f93-11e6-8571-c3c64c809f01.png)

Неправильно форматировал камент.

2016-10-31 18:25 UTC, IgorYarutkin commented on app/pages/styleguide.jade
> +>>>>>>> 571239f... Сверстать кнопку
А почему он при ребейзе не сказал, что есть конфликт?

2016-10-31 18:27 UTC, isqua commented on app/pages/styleguide.jade
> +>>>>>>> 571239f... Сверстать кнопку
Так может он сказал?

2016-10-31 18:28 UTC, IgorYarutkin commented on app/pages/styleguide.jade
> +>>>>>>> 571239f... Сверстать кнопку
Ну если бы он сказал. Я бы исправил

2016-10-31 18:28 UTC, IgorYarutkin commented
И в этой ветке у меня пропал блок `checkbox`

2016-10-31 18:34 UTC, isqua commented
Чекбокс и не должен быть в этой ветке, он же ещё не влит.

2016-10-31 18:59 UTC, IgorYarutkin commented on app/blocks/button/button.styl
> +	padding 12px 0
Сделал 10рх

2016-10-31 18:59 UTC, IgorYarutkin commented on app/blocks/button/button.styl
> +	font-size 17px
Сделал `line-height: 16px` как в макете

2016-10-31 19:02 UTC, IgorYarutkin commented on app/blocks/button/button.styl
> +		width 230px
Переходит в многострочную кнопку
![2016-10-31_22-00-42](https://cloud.githubusercontent.com/assets/16743649/19867640/a5c07ffa-9fb5-11e6-985e-72f76ceb5dc0.png)

2016-10-31 19:11 UTC, merged

2016-10-31 19:12 UTC, IgorYarutkin commented
Я хотел конфликт разрешить... А случайно уже его смерджил :(